"""Filesystem path constants — single source of truth.

The directory layout is in transition during the v1.0 refactor:

* PR-1 (this PR): paths point to the *current* ``agents/`` layout. Existing
  scripts continue to work unchanged.
* PR-4: paths will move to ``workspace/`` and existing tools will read these
  constants instead of hard-coding paths.

Computing paths from ``REPO_ROOT`` keeps everything robust to the package
being installed in ``-e`` mode or as a wheel.
"""

from __future__ import annotations

from pathlib import Path
from typing import Final

# This file lives at ``<repo>/src/duo_agents/config/paths.py``.
# parents[3] resolves to the repository root.
REPO_ROOT: Final[Path] = Path(__file__).resolve().parents[3]

# ── Asset directories (PR-4 will move these under ``workspace/``) ────────────
# Top-level directory containing all LLM-readable assets.
AGENTS_ASSETS_DIR: Final[Path] = REPO_ROOT / "agents"

# Subagent definitions (each subdir is one Task or QA agent).
SUBAGENTS_DIR: Final[Path] = AGENTS_ASSETS_DIR / "agents"

# Duet / Duet definitions (Actor-Critic pair definitions).
DUETS_DIR: Final[Path] = AGENTS_ASSETS_DIR / "duets"

# Templates used by the Subagent / Duet factories.
TEMPLATES_DIR: Final[Path] = AGENTS_ASSETS_DIR / "templates"

# Reusable Skills (Claude Code auto-discovers these via the ``.claude`` symlink).
SKILLS_DIR: Final[Path] = AGENTS_ASSETS_DIR / "skills"

# Topical rules (path-gated guardrails for agents).
RULES_DIR: Final[Path] = AGENTS_ASSETS_DIR / "rules"

# JSON Schema files (PR-2 will delete these when validators move to pydantic).
SCHEMAS_DIR: Final[Path] = AGENTS_ASSETS_DIR / "schemas"

# Persistent agent memory (auto-generated by tools).
AGENT_MEMORY_DIR: Final[Path] = AGENTS_ASSETS_DIR / "agent-memory"

# ── Manifest (HMAC-signed inventory of registered subagents) ─────────────────
# In the current layout the manifest lives inside ``agents/agents/``. PR-4
# will move it to ``manifest/manifest.json`` at the repo root.
MANIFEST_PATH: Final[Path] = SUBAGENTS_DIR / ".manifest.json"
MANIFEST_KEY_PATH: Final[Path] = REPO_ROOT / ".manifest-key"

# ── Evidence (run / eval output) ─────────────────────────────────────────────
EVIDENCE_DIR: Final[Path] = REPO_ROOT / "evidence"
EVIDENCE_SESSIONS_DIR: Final[Path] = EVIDENCE_DIR / "sessions"
EVIDENCE_DUETS_DIR: Final[Path] = EVIDENCE_DIR / "duets"
EVIDENCE_EVALS_DIR: Final[Path] = EVIDENCE_DIR / "evals"

# ── Tests ────────────────────────────────────────────────────────────────────
TESTS_DIR: Final[Path] = REPO_ROOT / "tests"
TESTS_FIXTURES_DIR: Final[Path] = TESTS_DIR / "fixtures"
TESTS_REPORTS_DIR: Final[Path] = TESTS_DIR / "reports"
